In [6]:
from itertools import groupby 
import torch
import numpy as np
import tensorflow as tf 

2024-04-12 13:39:51.663887: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-12 13:39:52.349953: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [7]:
edge_list = tf.convert_to_tensor(np.array([[0, 1],
        [0, 2],
        [0, 4],
        [1, 2],
        [1, 3],
        [2, 3],
        [2, 4],
        [3, 5],
        [3, 6],
        [4, 5],
        [5, 6]]))
edge_list

<tf.Tensor: shape=(11, 2), dtype=int64, numpy=
array([[0, 1],
       [0, 2],
       [0, 4],
       [1, 2],
       [1, 3],
       [2, 3],
       [2, 4],
       [3, 5],
       [3, 6],
       [4, 5],
       [5, 6]])>

In [20]:
np.array(edge_list)

array([[0, 1],
       [0, 2],
       [0, 4],
       [1, 2],
       [1, 3],
       [2, 3],
       [2, 4],
       [3, 5],
       [3, 6],
       [4, 5],
       [5, 6]])

In [42]:

duplicated_edge_list = np.vstack([edge_list, edge_list[:, ::-1]])
adj_dict={}
for k,g in groupby(np.array(duplicated_edge_list), lambda e: e[0]):
    if k not in adj_dict:
        adj_dict[k]=[]
    adj_dict[k].extend([pair[1] for pair in g])

adj_list = [nodes for nodes in adj_dict.values()]
adj_list

[[1, 2, 4],
 [2, 3, 0],
 [3, 4, 0, 1],
 [5, 6, 1, 2],
 [5, 0, 2],
 [6, 3, 4],
 [3, 5]]